### ISSUE TITLE
搜索后修改搜索条件就会报错退出

### ISSUE THREAD

**Issue by lushunming** [Greatwallcorner/TV-Multiplatform#7]
![FBvVj4ojAv](https://github.com/Greatwallcorner/TV-Multiplatform/assets/10239731/63e468aa-c352-412e-8a03-3c9620fa93fc)

**Comment by Greatwallcorner** [comment]
没有日志吗

**Comment by lushunming** [comment]
```
-05-09 10:09:34,851 DEBUG [DefaultDispatcher-worker-2] SpiderDebug: {}
2024-05-09 10:10:00,016 INFO  [AWT-EventQueue-0] Console: onPause
2024-05-09 10:10:00,017 INFO  [AWT-EventQueue-0] Console: onStop
2024-05-09 10:10:01,451 INFO  [AWT-EventQueue-0] Search: 开始搜索：红海行动
2024-05-09 10:10:01,456 INFO  [DefaultDispatcher-worker-8] Search: 站源：[云盘盘, 影搜, PanSearch┃搜索, 量子影视]
2024-05-09 10:10:01,920 DEBUG [DefaultDispatcher-worker-8] SpiderDebug: ++++++++++++量子-searchContent[{"vod_id":"http://www.lzizy9.com/index.php/vod/detail/id/58157.html","vod_name":"红海行动[电影解说]","vod_pic":"https://img.liangzipic.com/upload/vod/20230704-1/2b884998bf03be9d3066913a8a3bb9d5.jpg","vod_remarks":"2018 大陆"},{"vod_id":"http://www.lzizy9.com/index.php/vod/detail/id/6214.html","vod_name":"红海行动","vod_pic":"https://pic.liangzipic.com//upload/vod/20220616-1/d095427de882ce24b0956516c107e773.jpg","vod_remarks":"2018 大陆"}]
2024-05-09 10:10:01,921 DEBUG [DefaultDispatcher-worker-8] SpiderDebug: 量子影视,{"list":[{"vod_id":"http://www.lzizy9.com/index.php/vod/detail/id/58157.html","vod_name":"红海行动[电影解说]","vod_pic":"https://img.liangzipic.com/upload/vod/20230704-1/2b884998bf03be9d3066913a8a3bb9d5.jpg","vod_remarks":"2018 大陆"},{"vod_id":"http://www.lzizy9.com/index.php/vod/detail/id/6214.html","vod_name":"红海行动","vod_pic":"https://pic.liangzipic.com//upload/vod/20220616-1/d095427de882ce24b0956516c107e773.jpg","vod_remarks":"2018 大陆"}],"parse":0,"jx":0}
2024-05-09 10:10:01,922 DEBUG [DefaultDispatcher-worker-8] Search: 一个job执行完毕 List size:2
2024-05-09 10:10:02,508 DEBUG [DefaultDispatcher-worker-24] SpiderDebug: PanSearch┃搜索,{"list":[{"vod_id":"https://www.alipan.com/s/GgPehDva9BL","vod_name":"名称：《红海行动》4K超清","vod_pic":"https://cdn.pansearch.me/resources/49c4e4b727ba6b11833181f290e35214.jpg","vod_remarks":"2024-02-09T05:31:12+08:00"},{"vod_id":"https://www.aliyundrive.com/s/dLYCjSMvVqq","vod_name":"名称：红海行动 (2018) 1080p REMUX 原盘 外挂简中 【刮削】","vod_pic":"https://cdn.pansearch.me/resources/d5467d2addc66fbc9ff0f095594db929.jpg","vod_remarks":"2023-11-09T06:53:35+08:00"},{"vod_id":"https://www.aliyundrive.com/s/dLYCjSMvVqq","vod_name":"名称：红海行动 (2018) 1080p REMUX 原盘 外挂简中 【刮削】","vod_pic":"https://cdn.pansearch.me/resources/909d77a2ae063cfabd5541261a98568b.jpg","vod_remarks":"2023-11-09T06:52:30+08:00"},{"vod_id":"https://www.aliyundrive.com/s/Pw6PSMBhFbv","vod_name":"名称：红海行动 1080P","vod_pic":"https://cdn.pansearch.me/resources/216874ecc279c959f40d1a0b2034a54a.jpg","vod_remarks":"2023-01-02T07:09:11+08:00"},{"vod_id":"https://www.aliyundrive.com/s/9nomx4snbZq","vod_name":"名称：红海行动 (2018) 1080p原盘 [国英双语] [内封简英双字","vod_pic":"https://cdn.pansearch.me/resources/198091cd728a45a672ebe3852e219158.jpg","vod_remarks":"2022-10-27T11:56:30+08:00"},{"vod_id":"https://www.aliyundrive.com/s/Pw6PSMBhFbv","vod_name":"资源名称：红海行动 1080P","vod_pic":"https://cdn.pansearch.me/resources/09b376d27bba85a00d1933615f2a4f22.jpg","vod_remarks":"2023-01-02T06:52:48+08:00"},{"vod_id":"https://www.aliyundrive.com/s/Pw6PSMBhFbv","vod_name":"中文片名：红海行动 1080P","vod_pic":"https://cdn.pansearch.me/resources/0e2d24362f21eb6135232ab4850c9280.jpg","vod_remarks":"2023-01-02T06:47:07+08:00"},{"vod_id":"https://www.aliyundrive.com/s/Pw6PSMBhFbv","vod_name":"中文片名：红海行动 1080P","vod_pic":"https://cdn.pansearch.me/resources/1288dba084ae0aaaabf7b1474d9bf5c0.jpg","vod_remarks":"2023-01-02T06:50:58+08:00"},{"vod_id":"https://www.aliyundrive.com/s/9nomx4snbZq","vod_name":"资源名称：《红海行动》蓝光原盘REMUX [内封简、繁中字]","vod_pic":"https://cdn.pansearch.me/resources/0d6396511448c94fb7c755b4acbd1b93.jpg","vod_remarks":"2022-05-03T12:49:56+08:00"},{"vod_id":"https://www.aliyundrive.com/s/xrq8u5Eigzg","vod_name":"资源名称：红海行动 （2018）","vod_pic":"https://cdn.pansearch.me/resources/081321da4962a215b840faeeff69534d.jpg","vod_remarks":"2021-11-18T05:49:29+08:00"}],"parse":0,"jx":0}
2024-05-09 10:10:02,508 DEBUG [DefaultDispatcher-worker-24] Search: 一个job执行完毕 List size:12
2024-05-09 10:10:03,116 DEBUG [DefaultDispatcher-worker-9] SpiderDebug: 云盘盘,{"list":[],"parse":0,"jx":0}
2024-05-09 10:10:03,116 DEBUG [DefaultDispatcher-worker-9] Search: 一个job执行完毕 List size:12
2024-05-09 10:10:06,724 INFO  [AWT-EventQueue-0] Search: 开始搜索：红海
2024-05-09 10:10:06,725 INFO  [DefaultDispatcher-worker-19] Search: 站源：[玩偶, 找資源, 盘搜┃搜索, 易搜┃搜索]
2024-05-09 10:10:06,727 ERROR [AWT-EventQueue-0] main: 启动异常
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/java.util.concurrent.CopyOnWriteArrayList.elementAt(Unknown Source)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.get(Unknown Source)
	at com.corner.ui.search.SearchKt$SearchResult$2$1$2$1$1$invoke$$inlined$items$default$3.invoke(LazyDsl.kt:147)
	at com.corner.ui.search.SearchKt$SearchResult$2$1$2$1$1$invoke$$inlined$items$default$3.invoke(LazyDsl.kt:144)
	at androidx.compose.foundation.lazy.layout.LazyLayoutIntervalContent.getContentType(LazyLayoutIntervalContent.kt:49)
	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.getContentType(LazyListItemProvider.kt:87)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure(LazyListMeasuredItemProvider.kt:47)
	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-5IMabDg(LazyListMeasure.kt:195)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke-0kLqBqw(LazyList.kt:313)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:178)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:1107)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:709)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:646)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Padding.kt:397)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
	at androidx.compose.foundation.layout.UnspecifiedConstraintsNode.measure-3p2s80s(Size.kt:1074)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:1252)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2304)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:504)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:260)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:113)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:2617)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui(LayoutNode.kt:1145)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui$default$1718e334(LayoutNode.kt:1136)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:356)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:514)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:3491)
	at androidx.compose.ui.node.RootNodeOwner$OwnerImpl.measureAndLayout(RootNodeOwner.skiko.kt:290)
	at androidx.compose.ui.node.RootNodeOwner.measureAndLayout(RootNodeOwner.skiko.kt:187)
	at androidx.compose.ui.scene.MultiLayerComposeSceneImpl.measureAndLayout(MultiLayerComposeScene.skiko.kt:247)
	at androidx.compose.ui.scene.BaseComposeScene.doLayout(BaseComposeScene.skiko.kt:225)
	at androidx.compose.ui.scene.BaseComposeScene.render(BaseComposeScene.skiko.kt:9051)
	at androidx.compose.ui.scene.ComposeSceneMediator$DesktopSkikoView.onRender(ComposeSceneMediator.desktop.kt:523)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:548)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invokeSuspend(Direct3DRedrawer.kt:49)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: null
2024-05-09 10:10:06,990 DEBUG [DefaultDispatcher-worker-24] SpiderDebug: 盘搜┃搜索,{"list":[{"vod_id":"/s/Fe4rVBy7LBG7vVSzdIaKsVIOD6wPF","vod_name":"「红海行动」","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000"},{"vod_id":"/s/sdZCv9slXTOJl615WSwiFiBVLzsXc","vod_name":"红海行动","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000"},{"vod_id":"/s/be3qu04FAuBEwPf1NAYzw0QwgEsqL","vod_name":"红海船难 - 001 - 红海船难.mp4","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000"},{"vod_id":"/s/NdYTlvgEwLtTwnhjQ6t9LT7y4jQI1","vod_name":"红海船难 - 001 - 红海船难.mp4","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000"},{"vod_id":"/s/Ye6B3wzG0j2SvYjt1VlRk11bet8Sl","vod_name":"红海大漠（中国故事） - 梁子.mobi","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000"},{"vod_id":"/s/bdS1r2D80ANDovhOfwT9wwib5MEI1","vod_name":"红海大漠（中国故事） - 梁子.mobi","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000"},{"vod_id":"/s/KdPLSg2xBVmvm2ww1zHJFpw6FefIO","vod_name":"红海大漠（中国故事） - 梁子.mobi","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000"},{"vod_id":"/s/IecHoQwex0PCt2W6ULzGnmSaEhRxR","vod_name":"《红海魔影 国语版》国语版","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000"},{"vod_id":"/s/Key4mzHisl9rl79w7WlSYv7QIpV99","vod_name":"红海行动（2018）【动作 / 战争】红海行动主演: 张译 / 黄景瑜 / 海清 / 杜江 / 蒋璐霞","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000"},{"vod_id":"/s/lewo6RAzLCbsstjWGpo8sW3b340Iv","vod_name":"红海行动（2018）4K 军事/动作【电影】","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000"}],"parse":0,"jx":0}
2024-05-09 10:10:06,991 DEBUG [DefaultDispatcher-worker-24] Search: 一个job执行完毕 List size:10
2024-05-09 10:10:07,099 ERROR [DefaultDispatcher-worker-21] SiteViewModel: 影搜 search error
java.lang.NullPointerException: Cannot read field "msg" because "res" is null
	at com.github.catvod.spider.Yingso.searchContent(Yingso.java:27)
	at SiteViewModel.searchContent(SiteViewModel.kt:192)
	at com.corner.ui.decompose.component.DefaultSearchComponent$search$2$2$job$1.invokeSuspend(DefaultSearchComponent.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
2024-05-09 10:10:07,408 DEBUG [DefaultDispatcher-worker-12] SpiderDebug: 玩偶,{"list":[{"vod_id":"/index.php/voddetail/77343.html","vod_name":"红海行动","vod_pic":"https://img.liangzipic.com/upload/vod/20220616-1/d095427de882ce24b0956516c107e773.jpg","vod_remarks":"玩偶电影"}],"parse":0,"jx":0}
2024-05-09 10:10:07,408 DEBUG [DefaultDispatcher-worker-12] Search: 一个job执行完毕 List size:11
2024-05-09 10:10:07,941 DEBUG [DefaultDispatcher-worker-2] SpiderDebug: 找資源,{"list":[{"vod_id":"zjUEnjYPEMpea","vod_name":"No.09红海行动 4k-36.52亿","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000","vod_remarks":"2023-10-21 22:57"},{"vod_id":"TZ3O74VWoUba6","vod_name":"红海行动 1080P REMUX(原盘 蓝光)","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000","vod_remarks":"2023-01-02 14:57"},{"vod_id":"aBd3cMYIvTts4","vod_name":"红海行动","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000","vod_remarks":"2022-09-23 16:21"},{"vod_id":"91Y031Ut1Xc31","vod_name":"H红海行动","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000","vod_remarks":"2022-07-12 17:20"},{"vod_id":"69Q91VYNpu70j","vod_name":"红海行动","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000","vod_remarks":"2022-05-14 07:53"},{"vod_id":"0g5XvSoKz4s92","vod_name":"H-红海行动.Operation.Red.Sea.2018.Blu-ray.4K.H265.DTS-HD.MA7.1-DHTCLUB","vod_pic":"https://inews.gtimg.com/newsapp_bt/0/13263837859/1000","vod_remarks":"2022-04-22 21:20"}],"parse":0,"jx":0}
2024-05-09 10:10:07,941 DEBUG [DefaultDispatcher-worker-2] Search: 一个job执行完毕 List size:17
2024-05-09 10:10:10,432 DEBUG [DefaultDispatcher-worker-19] SpiderDebug: yiso 搜索次数限制
2024-05-09 10:10:10,433 DEBUG [DefaultDispatcher-worker-19] SpiderDebug: 易搜┃搜索,{}
2024-05-09 10:10:10,433 DEBUG [DefaultDispatcher-worker-19] Search: 一个job执行完毕 List size:17
2024-05-09 10:10:10,819 INFO  [AWT-EventQueue-0] Console: onDestroy
2024-05-09 10:10:15,015 DEBUG [KtorShutdownHook] application: Application stopping: io.ktor.server.application.Application@33542456
2024-05-09 10:10:15,016 DEBUG [KtorShutdownHook] application: Application stopped: io.ktor.server.application.Application@3

3542456
```


logfile :
[TV_2024-05-09.log](https://github.com/Greatwallcorner/TV-Multiplatform/files/15260629/TV_2024-05-09.log)
